### ISSUE TITLE
Improve ts types

### ISSUE THREAD

**Issue by dnlup** [immobiliare/fastify-sentry#318]
It looks like some types are not resolved on the `fastify.Sentry` instance as they would when using the `Sentry` instance.

**Comment by dnlup** [comment]
Maybe we should re-export all the `Sentry` types 🤔

**Comment by dnlup** [comment]
@mdoria12 wdyt?

**Comment by mdoria12** [comment]
I've tried by adding this at the end of the index.d.ts file:
`export * from '@sentry/types';`

and this solve my use case of using the `Severity` enum. 
But it seems that we should not use this approach anymore, because the enum is exported as a type and deprecated by Sentry itself, so i think we can keep the current types as is and close this issue for now.

@dnlup wdyt?

**Comment by dnlup** [comment]
I am thinking if we could have another use case similar to yours that could benefit of exporting all the types 🤔

**Comment by dnlup** [comment]
Maybe we can consider a rewrite in TS in a new release 🤔
